### ISSUE TITLE
rustywind-nvim causes gitsigns to error out when saving

### ISSUE THREAD

**Issue by flippette** [peytongraf/rustywind-nvim#1]
as per the title, i get this error whenever i save a file with `rustywind-nvim` formatting a git tracked file:

![image](https://github.com/peytongraf/rustywind-nvim/assets/43138244/7436ecae-c96a-4bc7-b94a-f0c0c176cfc1)

i can confirm enabling `rustywind-nvim` causes this to happen, and disabling it causes this to stop.

**Comment by peytongraf** [comment]
I have gitsigns installed but I haven't been able to reproduce this error.

**Comment by flippette** [comment]
can you try [my config](https://github.com/flippette/dotfiles) to see if it's a problem with it or with something else on my system?

**Comment by flippette** [comment]
btw, here's the full error message:

```
"templates/navbar.html" 22L, 575B written
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:69: attempt to index a nil value
stack traceback:
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/watcher.lua:65>
stack traceback:
	[C]: in function 'error'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function <...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:126>
```

**Comment by peytongraf** [comment]
I cloned your nvim config and did see the error once, but after modifying tailwind classes in git tracked html and tsx files I wasn't able to reproduce it again even after committing changes. I am using the git signs config that comes with NVChad and have no issues.
